### ISSUE TITLE
Add support for clickdown

### ISSUE THREAD

**Issue by gauntface** [gauntface/dpad-navigation#7]
Original step:

  - Apply styling for when the user clicks on a focused element via the clickdown class.
```css  
.grid-item.clickdown {
        background-color: rgb(189, 195, 199);
}
```
